package com.example.frontend.navigation

enum class AppScreen {
    ONBOARDING,
    LOGIN,
    SIGNUP,
    HOME,
    RECENT,
    FAVORITES,
    PROFILE,
    EDIT_PROFILE,
    PRIVACY_SECURITY,
    CHANGE_PASSWORD,
    LANGUAGE,
    COMMUTE_DETAIL,
    ROUTE_RESULTS,
    DESTINATION_SEARCH,
    TRIP_TRACKING,
    SETTINGS,
    FORGOT_PASSWORD,
    NAVIGATION
}