using backend.Models.Database;
using backend.Models.Routing;
using backend.Models.Valhalla;
using backend.Services.Routing;

namespace backend.Tests.Services.Routing;

/// <summary>
/// Production-derived regression coverage for the navOptimization routing
/// bugs. These use <see cref="ProductionTopologyFixture"/> -- three chained
/// jeepney routes, bending corridors, an off-corridor origin with its own
/// TODA and terminals placed along the corridor -- because the earlier
/// straight single-corridor fixtures could not express the shapes that
/// actually failed in production:
///
///   * a feeder riding ALONGSIDE a corridor and boarding much farther down
///     it, or swallowing an entire upstream jeepney leg (which changes the
///     route sequence, so a comparison keyed on that sequence never fired);
///   * a token jeepney hop bracketed by large feeders.
///
/// Nothing here reads the live database.
/// </summary>
public sealed class ProductionRoutingRegressionTests
{
    // -----------------------------------------------------------------
    // REGRESSION A -- the original screenshot.
    //
    // A tricycle must not ride along/around the jeepney corridor to board
    // farther down it when a sensible earlier boarding exists. In this
    // topology the trike can run 4.9 km beside corridor A and board corridor
    // B at its very start, skipping the whole of A -- which used to survive
    // because [B, C] and [A, B, C] were different comparison groups.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_TricycleDoesNotChaseTheCorridorToBoardFartherDown()
    {
        var plans = await PlanProductionTripAsync();

        Assert.NotEmpty(plans);
        foreach (var plan in plans)
        {
            var jeepneyLegs = JeepneyLegs(plan);
            if (jeepneyLegs.Count == 0)
                continue;

            Assert.Equal(ProductionTopologyFixture.RouteA, jeepneyLegs[0].RouteId);

            var originTrikeMeters = plan.OriginAccess.TrikeRideDistanceMeters ?? 0;
            Assert.True(
                originTrikeMeters <= 2_000,
                $"An origin tricycle of {originTrikeMeters:F0}m is riding the corridor, " +
                $"not reaching it; plan={Describe(plan)}");
        }
    }

    // -----------------------------------------------------------------
    // REGRESSION B -- the inverse. A token jeepney ride bracketed by large
    // feeders must not survive when staying on useful transit produces a
    // sensible journey. Both shapes are generated by this topology: an
    // 8 km origin trike onto a 1.7 km jeepney, and a 3.4 km jeepney followed
    // by a 5.8 km destination trike that replaces corridors B and C.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_TokenJeepneyWithOversizedFeedersDoesNotSurvive()
    {
        var plans = await PlanProductionTripAsync();

        Assert.NotEmpty(plans);
        foreach (var plan in plans)
        {
            var jeepneyLegs = JeepneyLegs(plan);
            if (jeepneyLegs.Count == 0)
                continue;

            var jeepneyMeters = jeepneyLegs.Sum(leg => leg.DistanceMeters);
            var feederMeters = plan.Legs
                .Where(leg => leg.Mode != AccessMode.Jeepney)
                .Sum(leg => leg.DistanceMeters);

            Assert.True(
                jeepneyMeters > feederMeters,
                $"The feeder modes are carrying this journey ({feederMeters:F0}m " +
                $"against {jeepneyMeters:F0}m of jeepney); plan={Describe(plan)}");

            Assert.All(jeepneyLegs, leg => Assert.True(
                leg.DistanceMeters >= 500,
                $"Token {leg.DistanceMeters:F0}m jeepney leg survived; plan={Describe(plan)}"));

            var destinationTrikeMeters = plan.DestinationAccess.TrikeRideDistanceMeters ?? 0;
            Assert.True(
                destinationTrikeMeters <= 2_000,
                $"A {destinationTrikeMeters:F0}m destination tricycle replaced remaining " +
                $"transit; plan={Describe(plan)}");
        }
    }

    // -----------------------------------------------------------------
    // REGRESSION C -- the expected good journey. A sensible tricycle feeder
    // onto three chained jeepney routes must survive every pruning stage.
    // The fare is asserted by component (one tricycle fare plus three
    // jeepney fares) rather than as an exact peso total, because the
    // tricycle fare follows confirmed road distance.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_SensibleTrikeFeederOntoThreeJeepneysSurvives()
    {
        var plans = await PlanProductionTripAsync();

        var journey = Assert.Single(
            plans,
            plan => plan.OriginAccess.Mode == AccessMode.Trike &&
                JeepneyLegs(plan).Select(leg => leg.RouteId).SequenceEqual(
                [
                    ProductionTopologyFixture.RouteA,
                    ProductionTopologyFixture.RouteB,
                    ProductionTopologyFixture.RouteC
                ]));

        Assert.Equal(
            ProductionTopologyFixture.OriginToda,
            journey.OriginAccess.TrikePointId);
        Assert.Equal(2, journey.TransferCount);
        Assert.All(JeepneyLegs(journey), leg => Assert.Equal(13, leg.FarePesos));

        // One ~1.4 km tricycle feeder (P50 at the configured tariff) plus
        // three P13 jeepney fares, and no destination fare at all.
        Assert.Equal(0, journey.DestinationAccess.TotalFarePesos);
        Assert.InRange(journey.OriginAccess.TotalFarePesos, 35, 65);
        Assert.InRange(journey.TotalFarePesos, 74, 104);

        Assert.Contains(
            journey.RecommendationType.Split(','),
            objective => objective is "efficient" or "fastest" or "cheapest");
    }

    // -----------------------------------------------------------------
    // REGRESSION D -- a legitimate off-corridor feeder. Rejecting shadowing
    // must never collapse into "always board earliest": corridor A is
    // reachable at 177 m and 471 m of route progress, and both boardings are
    // confirmed, yet the sensible journey boards at ~1.3 km because that is
    // where the tricycle from the origin's own TODA actually meets it.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_OffCorridorFeederToAUsefulBoardingPointSurvives()
    {
        var plans = await PlanProductionTripAsync();

        var journey = Assert.Single(
            plans,
            plan => plan.OriginAccess.Mode == AccessMode.Trike &&
                plan.OriginAccess.TrikePointId == ProductionTopologyFixture.OriginToda &&
                JeepneyLegs(plan).Count == 3);
        var firstJeepney = JeepneyLegs(journey)[0];

        Assert.True(
            firstJeepney.BoardLongitude > 120.5550,
            $"Expected the tricycle's own meeting point with corridor A, not the " +
            $"earliest reachable boarding; got {firstJeepney.BoardLongitude:F6}.");
        Assert.True(
            (journey.OriginAccess.TrikeRideDistanceMeters ?? 0) > 500,
            "This origin genuinely needs a tricycle feeder.");
    }

    // -----------------------------------------------------------------
    // REGRESSION E -- a legitimate earlier alight.
    //
    // The east corridor turns north at the same point the north corridor
    // begins, and the destination lies EAST of that turn. Staying on transit
    // past the turn is perfectly possible -- the second half of this test
    // proves the planner will happily do it for a northern destination -- but
    // for this destination it only moves the passenger away, so leaving at
    // the turn and taking a tricycle is right.
    //
    // Destination shadowing must therefore keep it. The rule is about the
    // EXTRA feeder distance an early alight costs against the transit it
    // gives up, never "stay on the jeepney longer": riding north here makes
    // the destination feeder longer, not shorter.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_EarlyAlightSurvivesWhenTheCorridorTurnsAway()
    {
        var eastbound = await PlanTurningCorridorTripAsync((15.1000, 120.5600));

        var journey = Assert.Single(
            eastbound,
            plan => plan.DestinationAccess.Mode == AccessMode.Trike);
        var jeepney = Assert.Single(JeepneyLegs(journey));

        Assert.Equal("E-EAST", jeepney.RouteId);
        Assert.True(
            jeepney.AlightLatitude < 15.1010,
            $"Expected the passenger to leave the corridor at the turn, got " +
            $"{jeepney.AlightLatitude:F6} -- riding north only moves away.");

        // Non-vacuity: staying on transit past the turn is a real, confirmed
        // option in this topology, so keeping the early alight above was a
        // decision rather than an absence of alternatives.
        var northbound = await PlanTurningCorridorTripAsync((15.1285, 120.5510));
        Assert.Contains(northbound, plan =>
            JeepneyLegs(plan).Any(leg => leg.RouteId == "E-NORTH"));
    }

    private static async Task<List<JeepneyTripPlan>> PlanTurningCorridorTripAsync(
        (double Latitude, double Longitude) destination)
    {
        var eastThenTurn = ProductionTopologyFixture.BuildDenseRoute(
            1,
            "E-EAST",
            "East corridor",
            [(15.1000, 120.5000), (15.1000, 120.5500), (15.1060, 120.5500)]);
        var northward = ProductionTopologyFixture.BuildDenseRoute(
            2,
            "E-NORTH",
            "North corridor",
            [(15.1055, 120.5505), (15.1300, 120.5505)]);

        var turnToda = ProductionTopologyFixture.BuildToda(
            1, "E-TODA-TURN", 15.0995, 120.5505);
        var northToda = ProductionTopologyFixture.BuildToda(
            2, "E-TODA-NORTH", 15.1200, 120.5512);

        var service = ProductionTopologyFixture.CreateService(
            options: ProductionTopologyFixture.DefaultOptions(
                maxTransfers: 1,
                maxWalkAccessDistanceMeters: 400),
            routes: [eastThenTurn, northward],
            trikePoints: [turnToda, northToda]);

        return await service.PlanTripsAsync(
            15.1000, 120.4995,
            destination.Latitude, destination.Longitude);
    }

    // -----------------------------------------------------------------
    // REGRESSION F -- grouping robustness.
    //
    // One corridor, one destination. A journey that boards ~900 m along the
    // corridor after a 1 km tricycle is plainly shadowing the corridor
    // against the journey that walks 450 m to board at the start. But that
    // journey also happens to finish differently: it leaves the jeepney a
    // couple of hundred metres earlier and takes a short tricycle from the
    // terminal beside the corridor instead of walking.
    //
    // Those finishing details are incidental to the boarding question, yet
    // the previous implementation folded them into a string group key
    // (alight progress bucketed into 300 m windows, plus destination access
    // mode and TODA id). The shadowing journey landed in a bucket of its own
    // and was never compared with anything, so it survived. Boarding must be
    // compared on the boarding evidence.
    // -----------------------------------------------------------------
    [Fact]
    public async Task PlanTripsAsync_ComparesBoardingDespiteIncidentalDownstreamDifferences()
    {
        var plans = await PlanGroupingScenarioAsync();

        Assert.NotEmpty(plans);

        // Both destination-access identities really are in play here, so the
        // shadowing journey genuinely differs from its comparison baseline in
        // more than where it boards.
        Assert.Contains(plans, plan =>
            plan.DestinationAccess.Mode == AccessMode.Trike);
        Assert.Contains(plans, plan =>
            plan.DestinationAccess.Mode == AccessMode.Walk);

        Assert.All(plans, plan =>
        {
            var jeepneyLegs = JeepneyLegs(plan);
            if (jeepneyLegs.Count == 0)
                return;

            Assert.True(
                jeepneyLegs[0].BoardLongitude < 120.5050,
                $"A tricycle riding ~1 km down the corridor to board must still be " +
                $"compared against the nearby boarding, whatever else differs " +
                $"downstream; got {jeepneyLegs[0].BoardLongitude:F6} for " +
                $"plan={Describe(plan)}.");
        });
    }

    private static async Task<List<JeepneyTripPlan>> PlanGroupingScenarioAsync()
    {
        var route = ProductionTopologyFixture.BuildDenseRoute(
            1,
            "F-CORRIDOR",
            "Comparison corridor",
            [(15.0000, 120.5000), (15.0000, 120.5600)]);

        var originToda = ProductionTopologyFixture.BuildToda(
            1, "F-TODA-ORIGIN", 15.0038, 120.5012);
        // Beside the corridor a little short of where the destination
        // projects onto it, so journeys finishing through this terminal
        // alight at a slightly different progress AND report a different
        // destination access identity.
        var destinationToda = ProductionTopologyFixture.BuildToda(
            2, "F-TODA-DESTINATION", 15.0002, 120.5279);

        var service = ProductionTopologyFixture.CreateService(
            options: ProductionTopologyFixture.DefaultOptions(
                maxTransfers: 0,
                maxWalkAccessDistanceMeters: 500,
                maxWalkToTrikePointMeters: 400,
                maxBoardingVariantsPerRoute: 8),
            valhalla: new RoadNetworkValhallaService(autoSpeedMetersPerSecond: 12.0),
            routes: [route],
            trikePoints: [originToda, destinationToda]);

        return await service.PlanTripsAsync(
            15.0035, 120.5010,
            15.0030, 120.5300);
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    private static async Task<List<JeepneyTripPlan>> PlanProductionTripAsync()
    {
        var service = ProductionTopologyFixture.CreateService();
        return await service.PlanTripsAsync(
            ProductionTopologyFixture.Origin.Latitude,
            ProductionTopologyFixture.Origin.Longitude,
            ProductionTopologyFixture.Destination.Latitude,
            ProductionTopologyFixture.Destination.Longitude);
    }

    private static List<JeepneyTripLeg> JeepneyLegs(JeepneyTripPlan plan) =>
        plan.Legs.Where(leg => leg.Mode == AccessMode.Jeepney).ToList();

    private static string Describe(JeepneyTripPlan plan) =>
        string.Join(" > ", plan.Legs.Select(leg => leg.Mode switch
        {
            AccessMode.Jeepney =>
                $"JEEP {leg.RouteId} {leg.DistanceMeters:F0}m/P{leg.FarePesos:F0}",
            AccessMode.Trike =>
                $"TRIKE {leg.TrikePointId} {leg.DistanceMeters:F0}m/P{leg.FarePesos:F0}",
            _ => $"WALK {leg.DistanceMeters:F0}m"
        })) + $" [{plan.RecommendationType}]";
}
