using backend.Models.Database;
using backend.Models.Routing;
using backend.Repositories;

namespace backend.Services.Assistant;

public sealed record PersistedJourney(RouteRecommendation Recommendation, JeepneyTripPlan Plan);

public interface IJourneyPlanPersistenceService
{
    Task<IReadOnlyList<PersistedJourney>> PersistAsync(
        Guid userId, double originLatitude, double originLongitude,
        string destinationName, double destinationLatitude, double destinationLongitude,
        decimal? budget, string? preference, IReadOnlyList<JeepneyTripPlan> plans,
        CancellationToken cancellationToken = default);
}

public sealed class JourneyPlanPersistenceService(
    ITripSearchRepository searches, IRouteRecommendationRepository recommendations,
    IRecommendationLegRepository legs, ITransportModeRepository modes,
    ITransportRouteRepository routes) : IJourneyPlanPersistenceService
{
    public async Task<IReadOnlyList<PersistedJourney>> PersistAsync(
        Guid userId, double originLatitude, double originLongitude,
        string destinationName, double destinationLatitude, double destinationLongitude,
        decimal? budget, string? preference, IReadOnlyList<JeepneyTripPlan> plans,
        CancellationToken cancellationToken = default)
    {
        var search = await searches.AddAsync(new TripSearch
        {
            UserId = userId, OriginName = "Current location",
            OriginLatitude = originLatitude, OriginLongitude = originLongitude,
            DestinationName = destinationName,
            DestinationLatitude = destinationLatitude, DestinationLongitude = destinationLongitude,
            Budget = budget, Preference = preference, PassengerCount = 1,
            RequestedAt = DateTime.UtcNow
        }, cancellationToken);
        var modeCache = new Dictionary<AccessMode, TransportMode>();
        var output = new List<PersistedJourney>();
        for (var rank = 0; rank < plans.Count; rank++)
        {
            var plan = plans[rank];
            var recommendation = await recommendations.AddAsync(new RouteRecommendation
            {
                TripSearchId = search.TripSearchId, RecommendationType = plan.RecommendationType,
                RankNumber = rank + 1, TotalFare = (decimal)plan.TotalFarePesos,
                TotalMinutes = (decimal)(plan.TotalTimeSeconds / 60),
                TotalDistanceMeters = (decimal)plan.Legs.Sum(item => item.DistanceMeters),
                WalkingDistanceMeters = (decimal)plan.Legs.Where(item => item.Mode == AccessMode.Walk).Sum(item => item.DistanceMeters),
                TransferCount = plan.TransferCount,
                RecommendationScore = (decimal)plan.GeneralizedCostPesos,
                Explanation = "Generated by Tuki's deterministic routing engine",
                GeneratedAt = DateTime.UtcNow
            }, cancellationToken);
            for (var index = 0; index < plan.Legs.Count; index++)
            {
                var source = plan.Legs[index];
                if (!modeCache.TryGetValue(source.Mode, out var mode))
                {
                    mode = await modes.GetByCodeAsync(source.Mode switch
                    {
                        AccessMode.Walk => "WALK", AccessMode.Trike => "TRICYCLE", _ => "JEEPNEY"
                    }, cancellationToken) ?? throw new InvalidOperationException(
                        $"Transport mode {source.Mode} is not configured.");
                    modeCache[source.Mode] = mode;
                }
                var route = source.RouteId is null ? null :
                    await routes.GetByRouteCodeAsync(source.RouteId, cancellationToken);
                await legs.AddAsync(new RecommendationLeg
                {
                    RecommendationId = recommendation.RecommendationId, LegOrder = index,
                    TransportModeId = mode.TransportModeId, RouteId = route?.RouteId,
                    FromName = source.RouteName, ToName = destinationName,
                    StartLatitude = source.OriginLatitude != 0 ? source.OriginLatitude : source.BoardLatitude,
                    StartLongitude = source.OriginLongitude != 0 ? source.OriginLongitude : source.BoardLongitude,
                    EndLatitude = source.DestinationLatitude != 0 ? source.DestinationLatitude : source.AlightLatitude,
                    EndLongitude = source.DestinationLongitude != 0 ? source.DestinationLongitude : source.AlightLongitude,
                    DistanceMeters = (decimal)source.DistanceMeters,
                    EstimatedMinutes = (decimal)(source.DurationSeconds / 60),
                    EstimatedFare = (decimal)source.FarePesos, CreatedAt = DateTime.UtcNow
                }, cancellationToken);
            }
            output.Add(new(recommendation, plan));
        }
        return output;
    }
}
