-- ============================================================================
-- TukiDb — All-in-one schema script
-- ============================================================================
-- Generated by concatenating, in run order:
--   1) TukiDbSchema.sql                                  (core schema)
--   2) TukiNavigationSchema.sql                           (Phase 2-6 navigation)
--   3) migrations/20260819_LocalUserAuthentication.sql    (local password auth)
--   4) migrations/20260819_NavigationSpeechAndSemanticLandmarks.sql
--
-- All four scripts are additive and idempotent; this file preserves that
-- property. Treat the individual files as the source of truth — regenerate
-- this one if any of them change or a new migration is added, rather than
-- editing it directly.
--
-- Usage: CREATE DATABASE TukiDb; then run this script against it.
-- ============================================================================

-- ── Part 1: TukiDbSchema.sql (core schema) ──────────────────────────────────

SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF SCHEMA_ID(N'dbo') IS NULL
    BEGIN
        EXEC(N'CREATE SCHEMA dbo');
    END;

    IF OBJECT_ID(N'dbo.UserProfiles', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.UserProfiles
        (
            UserId uniqueidentifier NOT NULL CONSTRAINT DF_UserProfiles_UserId DEFAULT (newsequentialid()),
            ExternalAuthProvider nvarchar(50) NULL,
            ExternalAuthId nvarchar(255) NULL,
            FirstName nvarchar(100) NULL,
            LastName nvarchar(100) NULL,
            Email nvarchar(255) NOT NULL,
            PhoneNumber nvarchar(30) NULL,
            Role nvarchar(30) NOT NULL CONSTRAINT DF_UserProfiles_Role DEFAULT (N'Passenger'),
            ProfileImageUrl nvarchar(500) NULL,
            IsActive bit NOT NULL CONSTRAINT DF_UserProfiles_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_UserProfiles_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NULL CONSTRAINT DF_UserProfiles_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_UserProfiles PRIMARY KEY (UserId)
        );
    END;

    IF OBJECT_ID(N'dbo.TransportModes', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TransportModes
        (
            TransportModeId int IDENTITY(1, 1) NOT NULL,
            ModeCode nvarchar(30) NOT NULL,
            ModeName nvarchar(100) NOT NULL,
            IsMotorized bit NOT NULL CONSTRAINT DF_TransportModes_IsMotorized DEFAULT (1),
            AllowsLiveDriver bit NOT NULL CONSTRAINT DF_TransportModes_AllowsLiveDriver DEFAULT (0),
            IconName nvarchar(100) NULL,
            IsActive bit NOT NULL CONSTRAINT DF_TransportModes_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TransportModes_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TransportModes PRIMARY KEY (TransportModeId)
        );
    END;

    IF OBJECT_ID(N'dbo.TransportStops', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TransportStops
        (
            TransportStopId bigint IDENTITY(1, 1) NOT NULL,
            StopCode nvarchar(50) NULL,
            StopName nvarchar(200) NOT NULL,
            Description nvarchar(500) NULL,
            StopType nvarchar(30) NOT NULL CONSTRAINT DF_TransportStops_StopType DEFAULT (N'JeepneyStop'),
            Address nvarchar(500) NULL,
            Latitude float NOT NULL,
            Longitude float NOT NULL,
            IsActive bit NOT NULL CONSTRAINT DF_TransportStops_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TransportStops_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NULL CONSTRAINT DF_TransportStops_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TransportStops PRIMARY KEY (TransportStopId)
        );
    END;

    IF OBJECT_ID(N'dbo.TransportRoutes', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TransportRoutes
        (
            TransportRouteId bigint IDENTITY(1, 1) NOT NULL,
            RouteCode nvarchar(50) NOT NULL,
            RouteName nvarchar(200) NOT NULL,
            TransportModeId int NOT NULL,
            StartTransportStopId bigint NULL,
            EndTransportStopId bigint NULL,
            OriginName nvarchar(200) NOT NULL CONSTRAINT DF_TransportRoutes_OriginName DEFAULT (N''),
            DestinationName nvarchar(200) NOT NULL CONSTRAINT DF_TransportRoutes_DestinationName DEFAULT (N''),
            DirectionName nvarchar(100) NULL,
            OperatorName nvarchar(200) NULL,
            Description nvarchar(1000) NULL,
            EncodedPolyline nvarchar(max) NULL,
            BaseFare decimal(10, 2) NULL,
            EstimatedDistanceMeters int NULL,
            EstimatedDurationSeconds int NULL,
            EstimatedTotalMinutes int NULL,
            AverageWaitingTimeSeconds int NULL,
            ServiceStartTime time NULL,
            ServiceEndTime time NULL,
            AverageHeadwayMinutes int NULL,
            OperatesMonday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesMonday DEFAULT (1),
            OperatesTuesday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesTuesday DEFAULT (1),
            OperatesWednesday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesWednesday DEFAULT (1),
            OperatesThursday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesThursday DEFAULT (1),
            OperatesFriday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesFriday DEFAULT (1),
            OperatesSaturday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesSaturday DEFAULT (1),
            OperatesSunday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesSunday DEFAULT (1),
            IsActive bit NOT NULL CONSTRAINT DF_TransportRoutes_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TransportRoutes_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NULL CONSTRAINT DF_TransportRoutes_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TransportRoutes PRIMARY KEY (TransportRouteId)
        );
    END;

    IF OBJECT_ID(N'dbo.RoutePoints', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RoutePoints
        (
            RoutePointId bigint IDENTITY(1, 1) NOT NULL,
            TransportRouteId bigint NOT NULL,
            PointOrder int NOT NULL,
            Latitude float NOT NULL,
            Longitude float NOT NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RoutePoints_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RoutePoints PRIMARY KEY (RoutePointId)
        );
    END;

    IF OBJECT_ID(N'dbo.RouteStops', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RouteStops
        (
            RouteStopId bigint IDENTITY(1, 1) NOT NULL,
            TransportRouteId bigint NOT NULL,
            TransportStopId bigint NOT NULL,
            StopOrder int NOT NULL,
            EstimatedTimeFromStartSeconds int NULL,
            DistanceFromRouteStartMeters int NULL,
            Instructions nvarchar(500) NULL,
            CanBoard bit NOT NULL CONSTRAINT DF_RouteStops_CanBoard DEFAULT (1),
            CanAlight bit NOT NULL CONSTRAINT DF_RouteStops_CanAlight DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteStops_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RouteStops PRIMARY KEY (RouteStopId)
        );
    END;

    IF OBJECT_ID(N'dbo.RouteWaypoints', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RouteWaypoints
        (
            RouteWaypointId bigint IDENTITY(1, 1) NOT NULL,
            TransportRouteId bigint NOT NULL,
            WaypointOrder int NOT NULL,
            Latitude float NOT NULL,
            Longitude float NOT NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteWaypoints_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RouteWaypoints PRIMARY KEY (RouteWaypointId)
        );
    END;

    IF OBJECT_ID(N'dbo.RouteSegments', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RouteSegments
        (
            RouteSegmentId bigint IDENTITY(1, 1) NOT NULL,
            TransportRouteId bigint NOT NULL,
            FromRouteStopId bigint NOT NULL,
            ToRouteStopId bigint NOT NULL,
            SegmentOrder int NOT NULL,
            DistanceMeters int NULL,
            EstimatedDurationSeconds int NULL,
            SegmentFare decimal(10, 2) NULL,
            IsBidirectional bit NOT NULL CONSTRAINT DF_RouteSegments_IsBidirectional DEFAULT (0),
            IsActive bit NOT NULL CONSTRAINT DF_RouteSegments_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteSegments_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteSegments_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RouteSegments PRIMARY KEY (RouteSegmentId)
        );
    END;

    IF OBJECT_ID(N'dbo.FareRules', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.FareRules
        (
            FareRuleId bigint IDENTITY(1, 1) NOT NULL,
            TransportModeId int NOT NULL,
            TransportRouteId bigint NOT NULL,
            PassengerType nvarchar(30) NOT NULL CONSTRAINT DF_FareRules_PassengerType DEFAULT (N'Regular'),
            FareType nvarchar(30) NOT NULL CONSTRAINT DF_FareRules_FareType DEFAULT (N'Base'),
            RuleName nvarchar(150) NOT NULL CONSTRAINT DF_FareRules_RuleName DEFAULT (N'Base Fare'),
            BaseFare decimal(10, 2) NOT NULL CONSTRAINT DF_FareRules_BaseFare DEFAULT (0),
            BaseDistanceKm decimal(10, 2) NULL,
            IncludedDistanceMeters int NULL,
            AdditionalFarePerKilometer decimal(10, 2) NULL,
            MinimumFare decimal(10, 2) NULL,
            MaximumFare decimal(10, 2) NULL,
            EffectiveFrom date NOT NULL CONSTRAINT DF_FareRules_EffectiveFrom DEFAULT (CONVERT(date, sysutcdatetime())),
            EffectiveUntil date NULL,
            IsActive bit NOT NULL CONSTRAINT DF_FareRules_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_FareRules_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_FareRules PRIMARY KEY (FareRuleId)
        );
    END;

    IF OBJECT_ID(N'dbo.TricyclePoints', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TricyclePoints
        (
            TricyclePointId bigint IDENTITY(1, 1) NOT NULL,
            TransportStopId bigint NULL,
            PointCode nvarchar(50) NOT NULL,
            PointName nvarchar(200) NOT NULL,
            Description nvarchar(500) NULL,
            Address nvarchar(500) NULL,
            OperatorName nvarchar(200) NULL,
            CenterLatitude float NOT NULL,
            CenterLongitude float NOT NULL,
            RadiusMeters int NOT NULL,
            BaseFare decimal(10, 2) NULL,
            FarePerKilometer decimal(10, 2) NULL,
            AverageWaitingTimeSeconds int NULL,
            ServiceStartTime time NULL,
            ServiceEndTime time NULL,
            IsActive bit NOT NULL CONSTRAINT DF_TricyclePoints_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TricyclePoints_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NULL CONSTRAINT DF_TricyclePoints_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TricyclePoints PRIMARY KEY (TricyclePointId)
        );
    END;

    IF OBJECT_ID(N'dbo.TransferConnections', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TransferConnections
        (
            TransferConnectionId bigint IDENTITY(1, 1) NOT NULL,
            FromTransportStopId bigint NOT NULL,
            ToTransportStopId bigint NOT NULL,
            MaximumWalkingDistanceMeters int NULL,
            EstimatedWalkingTimeSeconds int NULL,
            Instructions nvarchar(500) NULL,
            IsBidirectional bit NOT NULL CONSTRAINT DF_TransferConnections_IsBidirectional DEFAULT (1),
            IsActive bit NOT NULL CONSTRAINT DF_TransferConnections_IsActive DEFAULT (1),
            CONSTRAINT PK_TransferConnections PRIMARY KEY (TransferConnectionId)
        );
    END;

    IF OBJECT_ID(N'dbo.Drivers', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.Drivers
        (
            DriverId uniqueidentifier NOT NULL CONSTRAINT DF_Drivers_DriverId DEFAULT (newsequentialid()),
            UserId uniqueidentifier NOT NULL,
            LicenseNumber nvarchar(100) NULL,
            VerificationStatus nvarchar(30) NOT NULL CONSTRAINT DF_Drivers_VerificationStatus DEFAULT (N'PENDING'),
            HomeTerminalId bigint NULL,
            AverageRating decimal(3, 2) NULL,
            RatingCount int NOT NULL CONSTRAINT DF_Drivers_RatingCount DEFAULT (0),
            IsAvailable bit NOT NULL CONSTRAINT DF_Drivers_IsAvailable DEFAULT (0),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_Drivers_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NULL CONSTRAINT DF_Drivers_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_Drivers PRIMARY KEY (DriverId)
        );
    END;

    IF OBJECT_ID(N'dbo.DriverVehicles', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.DriverVehicles
        (
            DriverVehicleId uniqueidentifier NOT NULL CONSTRAINT DF_DriverVehicles_DriverVehicleId DEFAULT (newsequentialid()),
            DriverId uniqueidentifier NOT NULL,
            TransportModeId int NOT NULL,
            TricyclePointId bigint NULL,
            VehicleType nvarchar(30) NOT NULL CONSTRAINT DF_DriverVehicles_VehicleType DEFAULT (N'Tricycle'),
            PlateNumber nvarchar(50) NULL,
            BodyNumber nvarchar(50) NULL,
            Color nvarchar(50) NULL,
            PassengerCapacity int NOT NULL CONSTRAINT DF_DriverVehicles_PassengerCapacity DEFAULT (1),
            IsActive bit NOT NULL CONSTRAINT DF_DriverVehicles_IsActive DEFAULT (1),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_DriverVehicles_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_DriverVehicles PRIMARY KEY (DriverVehicleId)
        );
    END;

    IF OBJECT_ID(N'dbo.DriverLocations', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.DriverLocations
        (
            DriverLocationId bigint IDENTITY(1, 1) NOT NULL,
            DriverId uniqueidentifier NOT NULL,
            Latitude float NOT NULL,
            Longitude float NOT NULL,
            HeadingDegrees float NULL,
            SpeedKilometersPerHour float NULL,
            AccuracyMeters float NULL,
            RecordedAt datetime2(7) NOT NULL CONSTRAINT DF_DriverLocations_RecordedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_DriverLocations PRIMARY KEY (DriverLocationId)
        );
    END;

    IF OBJECT_ID(N'dbo.DriverAvailabilitySessions', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.DriverAvailabilitySessions
        (
            DriverAvailabilitySessionId bigint IDENTITY(1, 1) NOT NULL,
            DriverId uniqueidentifier NOT NULL,
            DriverVehicleId uniqueidentifier NULL,
            DestinationStopId bigint NULL,
            TricyclePointId bigint NULL,
            DestinationName nvarchar(250) NULL,
            DestinationLatitude float NULL,
            DestinationLongitude float NULL,
            AvailableSeats int NOT NULL CONSTRAINT DF_DriverAvailability_AvailableSeats DEFAULT (1),
            MaximumDetourMeters decimal(10, 2) NOT NULL CONSTRAINT DF_DriverAvailability_MaximumDetourMeters DEFAULT (1000),
            Status nvarchar(30) NOT NULL CONSTRAINT DF_DriverAvailability_Status DEFAULT (N'AVAILABLE'),
            StartedAt datetime2(7) NOT NULL CONSTRAINT DF_DriverAvailability_StartedAt DEFAULT (sysutcdatetime()),
            EndedAt datetime2(7) NULL,
            CONSTRAINT PK_DriverAvailabilitySessions PRIMARY KEY (DriverAvailabilitySessionId)
        );
    END;

    IF OBJECT_ID(N'dbo.PassengerRideRequests', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.PassengerRideRequests
        (
            PassengerRideRequestId uniqueidentifier NOT NULL CONSTRAINT DF_PassengerRideRequests_RequestId DEFAULT (newsequentialid()),
            PassengerUserId uniqueidentifier NOT NULL,
            TransportModeId int NULL,
            TricyclePointId bigint NULL,
            PickupName nvarchar(250) NULL,
            PickupLatitude float NOT NULL,
            PickupLongitude float NOT NULL,
            DropoffName nvarchar(250) NULL,
            DestinationLatitude float NOT NULL,
            DestinationLongitude float NOT NULL,
            PassengerCount int NOT NULL CONSTRAINT DF_PassengerRideRequests_PassengerCount DEFAULT (1),
            MaxBudget decimal(10, 2) NULL,
            EstimatedFare decimal(10, 2) NULL,
            EstimatedDistanceMeters int NULL,
            EstimatedDurationSeconds int NULL,
            Status nvarchar(30) NOT NULL CONSTRAINT DF_PassengerRideRequests_Status DEFAULT (N'SEARCHING'),
            RequestedAt datetime2(7) NOT NULL CONSTRAINT DF_PassengerRideRequests_RequestedAt DEFAULT (sysutcdatetime()),
            ExpiresAt datetime2(7) NULL,
            CancelledAt datetime2(7) NULL,
            CompletedAt datetime2(7) NULL,
            UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_PassengerRideRequests_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_PassengerRideRequests PRIMARY KEY (PassengerRideRequestId)
        );
    END;

    IF OBJECT_ID(N'dbo.RideMatches', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RideMatches
        (
            RideMatchId uniqueidentifier NOT NULL CONSTRAINT DF_RideMatches_RideMatchId DEFAULT (newsequentialid()),
            PassengerRideRequestId uniqueidentifier NOT NULL,
            DriverId uniqueidentifier NOT NULL,
            SessionId bigint NULL,
            DriverVehicleId uniqueidentifier NULL,
            PickupDistanceMeters decimal(10, 2) NULL,
            DetourDistanceMeters decimal(10, 2) NULL,
            EstimatedPickupMinutes decimal(10, 2) NULL,
            EstimatedTripMinutes decimal(10, 2) NULL,
            OfferedFare decimal(10, 2) NULL,
            MatchScore decimal(12, 6) NULL,
            Status nvarchar(30) NOT NULL CONSTRAINT DF_RideMatches_Status DEFAULT (N'OFFERED'),
            MatchedAt datetime2(7) NOT NULL CONSTRAINT DF_RideMatches_MatchedAt DEFAULT (sysutcdatetime()),
            RespondedAt datetime2(7) NULL,
            CompletedAt datetime2(7) NULL,
            CONSTRAINT PK_RideMatches PRIMARY KEY (RideMatchId)
        );
    END;

    IF OBJECT_ID(N'dbo.TripSearches', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TripSearches
        (
            TripSearchId uniqueidentifier NOT NULL CONSTRAINT DF_TripSearches_TripSearchId DEFAULT (newsequentialid()),
            UserId uniqueidentifier NULL,
            OriginName nvarchar(250) NULL,
            OriginLatitude float NOT NULL,
            OriginLongitude float NOT NULL,
            DestinationName nvarchar(250) NULL,
            DestinationLatitude float NOT NULL,
            DestinationLongitude float NOT NULL,
            Budget decimal(10, 2) NULL,
            PassengerCount int NOT NULL CONSTRAINT DF_TripSearches_PassengerCount DEFAULT (1),
            Preference nvarchar(30) NULL,
            RequestedAt datetime2(7) NOT NULL CONSTRAINT DF_TripSearches_RequestedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TripSearches PRIMARY KEY (TripSearchId)
        );
    END;

    IF OBJECT_ID(N'dbo.RouteRecommendations', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RouteRecommendations
        (
            RecommendationId uniqueidentifier NOT NULL CONSTRAINT DF_RouteRecommendations_RecommendationId DEFAULT (newsequentialid()),
            TripSearchId uniqueidentifier NOT NULL,
            RecommendationType nvarchar(30) NOT NULL,
            RankNumber int NOT NULL CONSTRAINT DF_RouteRecommendations_RankNumber DEFAULT (1),
            TotalFare decimal(10, 2) NOT NULL,
            TotalMinutes decimal(10, 2) NOT NULL,
            TotalDistanceMeters decimal(12, 2) NULL,
            WalkingDistanceMeters decimal(12, 2) NOT NULL,
            TransferCount int NOT NULL CONSTRAINT DF_RouteRecommendations_TransferCount DEFAULT (0),
            RecommendationScore decimal(12, 6) NULL,
            Explanation nvarchar(max) NULL,
            GeneratedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteRecommendations_GeneratedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RouteRecommendations PRIMARY KEY (RecommendationId)
        );
    END;

    IF OBJECT_ID(N'dbo.RecommendationLegs', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.RecommendationLegs
        (
            LegId uniqueidentifier NOT NULL CONSTRAINT DF_RecommendationLegs_LegId DEFAULT (newsequentialid()),
            RecommendationId uniqueidentifier NOT NULL,
            LegOrder int NOT NULL,
            TransportModeId int NOT NULL,
            TransportRouteId bigint NULL,
            FromTransportStopId bigint NULL,
            ToTransportStopId bigint NULL,
            FromName nvarchar(250) NULL,
            ToName nvarchar(250) NULL,
            StartLatitude float NULL,
            StartLongitude float NULL,
            EndLatitude float NULL,
            EndLongitude float NULL,
            DistanceMeters decimal(12, 2) NULL,
            EstimatedMinutes decimal(10, 2) NOT NULL CONSTRAINT DF_RecommendationLegs_EstimatedMinutes DEFAULT (0),
            EstimatedFare decimal(10, 2) NOT NULL CONSTRAINT DF_RecommendationLegs_EstimatedFare DEFAULT (0),
            Instructions nvarchar(max) NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RecommendationLegs_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_RecommendationLegs PRIMARY KEY (LegId)
        );
    END;

    IF OBJECT_ID(N'dbo.PassengerTrips', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.PassengerTrips
        (
            PassengerTripId uniqueidentifier NOT NULL CONSTRAINT DF_PassengerTrips_PassengerTripId DEFAULT (newsequentialid()),
            UserId uniqueidentifier NOT NULL,
            RecommendationId uniqueidentifier NOT NULL,
            CurrentLegOrder int NOT NULL CONSTRAINT DF_PassengerTrips_CurrentLegOrder DEFAULT (1),
            Status nvarchar(30) NOT NULL CONSTRAINT DF_PassengerTrips_Status DEFAULT (N'PLANNED'),
            StartedAt datetime2(7) NULL,
            CompletedAt datetime2(7) NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_PassengerTrips_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_PassengerTrips_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_PassengerTrips PRIMARY KEY (PassengerTripId)
        );
    END;

    IF OBJECT_ID(N'dbo.TripAlerts', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TripAlerts
        (
            AlertId uniqueidentifier NOT NULL CONSTRAINT DF_TripAlerts_AlertId DEFAULT (newsequentialid()),
            PassengerTripId uniqueidentifier NOT NULL,
            LegId uniqueidentifier NULL,
            TargetTransportStopId bigint NULL,
            AlertType nvarchar(40) NOT NULL,
            Title nvarchar(150) NULL,
            Message nvarchar(max) NOT NULL,
            TriggerDistanceMeters decimal(10, 2) NULL,
            IsTriggered bit NOT NULL CONSTRAINT DF_TripAlerts_IsTriggered DEFAULT (0),
            TriggeredAt datetime2(7) NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TripAlerts_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TripAlerts PRIMARY KEY (AlertId)
        );
    END;

    IF OBJECT_ID(N'dbo.ChatConversations', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.ChatConversations
        (
            ConversationId uniqueidentifier NOT NULL CONSTRAINT DF_ChatConversations_ConversationId DEFAULT (newsequentialid()),
            UserId uniqueidentifier NOT NULL,
            Title nvarchar(200) NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_ChatConversations_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_ChatConversations_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_ChatConversations PRIMARY KEY (ConversationId)
        );
    END;

    IF OBJECT_ID(N'dbo.ChatMessages', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.ChatMessages
        (
            MessageId uniqueidentifier NOT NULL CONSTRAINT DF_ChatMessages_MessageId DEFAULT (newsequentialid()),
            ConversationId uniqueidentifier NOT NULL,
            Sender nvarchar(20) NOT NULL,
            Message nvarchar(max) NOT NULL,
            ExtractedBudget decimal(10, 2) NULL,
            ExtractedOrigin nvarchar(250) NULL,
            ExtractedDestination nvarchar(250) NULL,
            TripSearchId uniqueidentifier NULL,
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_ChatMessages_CreatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_ChatMessages PRIMARY KEY (MessageId)
        );
    END;

    IF COL_LENGTH(N'dbo.UserProfiles', N'ProfileImageUrl') IS NULL ALTER TABLE dbo.UserProfiles ADD ProfileImageUrl nvarchar(500) NULL;
    IF COL_LENGTH(N'dbo.UserProfiles', N'UpdatedAt') IS NULL ALTER TABLE dbo.UserProfiles ADD UpdatedAt datetime2(7) NULL CONSTRAINT DF_UserProfiles_UpdatedAt_Add DEFAULT (sysutcdatetime());

    IF COL_LENGTH(N'dbo.TransportModes', N'IsMotorized') IS NULL ALTER TABLE dbo.TransportModes ADD IsMotorized bit NOT NULL CONSTRAINT DF_TransportModes_IsMotorized_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportModes', N'AllowsLiveDriver') IS NULL ALTER TABLE dbo.TransportModes ADD AllowsLiveDriver bit NOT NULL CONSTRAINT DF_TransportModes_AllowsLiveDriver_Add DEFAULT (0) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportModes', N'IconName') IS NULL ALTER TABLE dbo.TransportModes ADD IconName nvarchar(100) NULL;
    IF COL_LENGTH(N'dbo.TransportModes', N'CreatedAt') IS NULL ALTER TABLE dbo.TransportModes ADD CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TransportModes_CreatedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;

    IF COL_LENGTH(N'dbo.TransportRoutes', N'StartTransportStopId') IS NULL ALTER TABLE dbo.TransportRoutes ADD StartTransportStopId bigint NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'EndTransportStopId') IS NULL ALTER TABLE dbo.TransportRoutes ADD EndTransportStopId bigint NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'BaseFare') IS NULL ALTER TABLE dbo.TransportRoutes ADD BaseFare decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'EncodedPolyline') IS NULL ALTER TABLE dbo.TransportRoutes ADD EncodedPolyline nvarchar(max) NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'EstimatedTotalMinutes') IS NULL ALTER TABLE dbo.TransportRoutes ADD EstimatedTotalMinutes int NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'AverageHeadwayMinutes') IS NULL ALTER TABLE dbo.TransportRoutes ADD AverageHeadwayMinutes int NULL;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesMonday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesMonday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesMonday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesTuesday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesTuesday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesTuesday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesWednesday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesWednesday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesWednesday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesThursday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesThursday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesThursday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesFriday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesFriday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesFriday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesSaturday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesSaturday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesSaturday_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.TransportRoutes', N'OperatesSunday') IS NULL ALTER TABLE dbo.TransportRoutes ADD OperatesSunday bit NOT NULL CONSTRAINT DF_TransportRoutes_OperatesSunday_Add DEFAULT (1) WITH VALUES;

    IF COL_LENGTH(N'dbo.RouteStops', N'DistanceFromRouteStartMeters') IS NULL ALTER TABLE dbo.RouteStops ADD DistanceFromRouteStartMeters int NULL;
    IF COL_LENGTH(N'dbo.RouteStops', N'CreatedAt') IS NULL ALTER TABLE dbo.RouteStops ADD CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteStops_CreatedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;

    IF COL_LENGTH(N'dbo.RouteSegments', N'IsBidirectional') IS NULL ALTER TABLE dbo.RouteSegments ADD IsBidirectional bit NOT NULL CONSTRAINT DF_RouteSegments_IsBidirectional_Add DEFAULT (0) WITH VALUES;
    IF COL_LENGTH(N'dbo.RouteSegments', N'CreatedAt') IS NULL ALTER TABLE dbo.RouteSegments ADD CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteSegments_CreatedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;
    IF COL_LENGTH(N'dbo.RouteSegments', N'UpdatedAt') IS NULL ALTER TABLE dbo.RouteSegments ADD UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_RouteSegments_UpdatedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;

    IF COL_LENGTH(N'dbo.FareRules', N'TransportModeId') IS NULL ALTER TABLE dbo.FareRules ADD TransportModeId int NULL;
    IF COL_LENGTH(N'dbo.FareRules', N'RuleName') IS NULL ALTER TABLE dbo.FareRules ADD RuleName nvarchar(150) NOT NULL CONSTRAINT DF_FareRules_RuleName_Add DEFAULT (N'Base Fare') WITH VALUES;
    IF COL_LENGTH(N'dbo.FareRules', N'BaseDistanceKm') IS NULL ALTER TABLE dbo.FareRules ADD BaseDistanceKm decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.FareRules', N'IncludedDistanceMeters') IS NULL ALTER TABLE dbo.FareRules ADD IncludedDistanceMeters int NULL;
    IF COL_LENGTH(N'dbo.TricyclePoints', N'UpdatedAt') IS NULL ALTER TABLE dbo.TricyclePoints ADD UpdatedAt datetime2(7) NULL CONSTRAINT DF_TricyclePoints_UpdatedAt_Add DEFAULT (sysutcdatetime());

    IF COL_LENGTH(N'dbo.Drivers', N'HomeTerminalId') IS NULL ALTER TABLE dbo.Drivers ADD HomeTerminalId bigint NULL;
    IF COL_LENGTH(N'dbo.Drivers', N'AverageRating') IS NULL ALTER TABLE dbo.Drivers ADD AverageRating decimal(3, 2) NULL;
    IF COL_LENGTH(N'dbo.Drivers', N'RatingCount') IS NULL ALTER TABLE dbo.Drivers ADD RatingCount int NOT NULL CONSTRAINT DF_Drivers_RatingCount_Add DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.DriverVehicles', N'TransportModeId') IS NULL ALTER TABLE dbo.DriverVehicles ADD TransportModeId int NULL;
    IF COL_LENGTH(N'dbo.DriverVehicles', N'TricyclePointId') IS NULL ALTER TABLE dbo.DriverVehicles ADD TricyclePointId bigint NULL;

    IF COL_LENGTH(N'dbo.DriverLocations', N'DriverLocationId') IS NULL
        ALTER TABLE dbo.DriverLocations ADD DriverLocationId bigint IDENTITY(1, 1) NOT NULL;
    IF COL_LENGTH(N'dbo.DriverLocations', N'RecordedAt') IS NULL
        ALTER TABLE dbo.DriverLocations ADD RecordedAt datetime2(7) NOT NULL CONSTRAINT DF_DriverLocations_RecordedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;
    IF COL_LENGTH(N'dbo.DriverLocations', N'SpeedKilometersPerHour') IS NULL
        ALTER TABLE dbo.DriverLocations ADD SpeedKilometersPerHour float NULL;

    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DestinationStopId') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD DestinationStopId bigint NULL;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'TricyclePointId') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD TricyclePointId bigint NULL;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DestinationName') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD DestinationName nvarchar(250) NULL;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DestinationLatitude') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD DestinationLatitude float NULL;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DestinationLongitude') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD DestinationLongitude float NULL;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'AvailableSeats') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD AvailableSeats int NOT NULL CONSTRAINT DF_DriverAvailability_AvailableSeats_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'MaximumDetourMeters') IS NULL ALTER TABLE dbo.DriverAvailabilitySessions ADD MaximumDetourMeters decimal(10, 2) NOT NULL CONSTRAINT DF_DriverAvailability_MaximumDetourMeters_Add DEFAULT (1000) WITH VALUES;

    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'TransportModeId') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD TransportModeId int NULL;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'PickupName') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD PickupName nvarchar(250) NULL;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'DropoffName') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD DropoffName nvarchar(250) NULL;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'PassengerCount') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD PassengerCount int NOT NULL CONSTRAINT DF_PassengerRideRequests_PassengerCount_Add DEFAULT (1) WITH VALUES;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'MaxBudget') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD MaxBudget decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'ExpiresAt') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD ExpiresAt datetime2(7) NULL;
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'UpdatedAt') IS NULL ALTER TABLE dbo.PassengerRideRequests ADD UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_PassengerRideRequests_UpdatedAt_Add DEFAULT (sysutcdatetime()) WITH VALUES;

    IF COL_LENGTH(N'dbo.RideMatches', N'SessionId') IS NULL ALTER TABLE dbo.RideMatches ADD SessionId bigint NULL;
    IF COL_LENGTH(N'dbo.RideMatches', N'PickupDistanceMeters') IS NULL ALTER TABLE dbo.RideMatches ADD PickupDistanceMeters decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.RideMatches', N'DetourDistanceMeters') IS NULL ALTER TABLE dbo.RideMatches ADD DetourDistanceMeters decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.RideMatches', N'EstimatedPickupMinutes') IS NULL ALTER TABLE dbo.RideMatches ADD EstimatedPickupMinutes decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.RideMatches', N'EstimatedTripMinutes') IS NULL ALTER TABLE dbo.RideMatches ADD EstimatedTripMinutes decimal(10, 2) NULL;
    IF COL_LENGTH(N'dbo.RideMatches', N'MatchScore') IS NULL ALTER TABLE dbo.RideMatches ADD MatchScore decimal(12, 6) NULL;

    EXEC sys.sp_executesql N'
        IF NOT EXISTS (SELECT 1 FROM dbo.TransportModes WHERE ModeCode = N''WALK'')
        BEGIN
            INSERT dbo.TransportModes (ModeCode, ModeName, IsMotorized, AllowsLiveDriver, IconName, IsActive)
            VALUES (N''WALK'', N''Walk'', CONVERT(bit, 0), CONVERT(bit, 0), N''walk'', CONVERT(bit, 1));
        END
        ELSE
        BEGIN
            UPDATE dbo.TransportModes
            SET IsMotorized = CONVERT(bit, 0),
                AllowsLiveDriver = CONVERT(bit, 0),
                IconName = COALESCE(IconName, N''walk''),
                IsActive = CONVERT(bit, 1)
            WHERE ModeCode = N''WALK'';
        END;

        IF NOT EXISTS (SELECT 1 FROM dbo.TransportModes WHERE ModeCode = N''JEEPNEY'')
        BEGIN
            INSERT dbo.TransportModes (ModeCode, ModeName, IsMotorized, AllowsLiveDriver, IconName, IsActive)
            VALUES (N''JEEPNEY'', N''Jeepney'', CONVERT(bit, 1), CONVERT(bit, 0), N''bus'', CONVERT(bit, 1));
        END
        ELSE
        BEGIN
            UPDATE dbo.TransportModes
            SET IsMotorized = CONVERT(bit, 1),
                AllowsLiveDriver = CONVERT(bit, 0),
                IconName = COALESCE(IconName, N''bus''),
                IsActive = CONVERT(bit, 1)
            WHERE ModeCode = N''JEEPNEY'';
        END;

        IF NOT EXISTS (SELECT 1 FROM dbo.TransportModes WHERE ModeCode = N''TRICYCLE'')
        BEGIN
            INSERT dbo.TransportModes (ModeCode, ModeName, IsMotorized, AllowsLiveDriver, IconName, IsActive)
            VALUES (N''TRICYCLE'', N''Tricycle'', CONVERT(bit, 1), CONVERT(bit, 1), N''bike'', CONVERT(bit, 1));
        END
        ELSE
        BEGIN
            UPDATE dbo.TransportModes
            SET IsMotorized = CONVERT(bit, 1),
                AllowsLiveDriver = CONVERT(bit, 1),
                IconName = COALESCE(IconName, N''bike''),
                IsActive = CONVERT(bit, 1)
            WHERE ModeCode = N''TRICYCLE'';
        END;';

    IF COL_LENGTH(N'dbo.FareRules', N'TransportModeId') IS NOT NULL
       AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.FareRules') AND name = N'TransportModeId' AND is_nullable = 1)
    BEGIN
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT 1 FROM dbo.FareRules WHERE TransportModeId IS NULL)
                ALTER TABLE dbo.FareRules ALTER COLUMN TransportModeId int NOT NULL;';
    END;

    IF COL_LENGTH(N'dbo.DriverVehicles', N'TransportModeId') IS NOT NULL
       AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.DriverVehicles') AND name = N'TransportModeId' AND is_nullable = 1)
    BEGIN
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT 1 FROM dbo.DriverVehicles WHERE TransportModeId IS NULL)
                ALTER TABLE dbo.DriverVehicles ALTER COLUMN TransportModeId int NOT NULL;';
    END;

    IF COL_LENGTH(N'dbo.UserProfiles', N'Email') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.UserProfiles') AND name = N'UX_UserProfiles_Email')
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT Email FROM dbo.UserProfiles GROUP BY Email HAVING COUNT_BIG(*) > 1)
                CREATE UNIQUE INDEX UX_UserProfiles_Email ON dbo.UserProfiles (Email);';

    IF COL_LENGTH(N'dbo.UserProfiles', N'ExternalAuthProvider') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'ExternalAuthId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.UserProfiles') AND name = N'UX_UserProfiles_ExternalAuthentication')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_UserProfiles_ExternalAuthentication ON dbo.UserProfiles (ExternalAuthProvider, ExternalAuthId) WHERE ExternalAuthProvider IS NOT NULL AND ExternalAuthId IS NOT NULL;';

    IF COL_LENGTH(N'dbo.TransportModes', N'ModeCode') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportModes') AND name = N'UX_TransportModes_ModeCode')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_TransportModes_ModeCode ON dbo.TransportModes (ModeCode);';

    IF COL_LENGTH(N'dbo.TransportModes', N'ModeName') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportModes') AND name = N'UX_TransportModes_ModeName')
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT ModeName FROM dbo.TransportModes GROUP BY ModeName HAVING COUNT_BIG(*) > 1)
                CREATE UNIQUE INDEX UX_TransportModes_ModeName ON dbo.TransportModes (ModeName);';

    IF COL_LENGTH(N'dbo.TransportStops', N'Latitude') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'Longitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportStops') AND name = N'IX_TransportStops_Coordinates')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TransportStops_Coordinates ON dbo.TransportStops (Latitude, Longitude);';

    IF COL_LENGTH(N'dbo.TransportStops', N'StopName') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportStops') AND name = N'IX_TransportStops_StopName')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TransportStops_StopName ON dbo.TransportStops (StopName);';

    IF COL_LENGTH(N'dbo.TransportStops', N'StopCode') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportStops') AND name = N'UX_TransportStops_StopCode')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_TransportStops_StopCode ON dbo.TransportStops (StopCode) WHERE StopCode IS NOT NULL;';

    IF COL_LENGTH(N'dbo.TransportRoutes', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'IsActive') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportRoutes') AND name = N'IX_TransportRoutes_TransportMode')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TransportRoutes_TransportMode ON dbo.TransportRoutes (TransportModeId, IsActive);';

    IF COL_LENGTH(N'dbo.TransportRoutes', N'RouteCode') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransportRoutes') AND name = N'UX_TransportRoutes_RouteCode')
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT RouteCode FROM dbo.TransportRoutes GROUP BY RouteCode HAVING COUNT_BIG(*) > 1)
                CREATE UNIQUE INDEX UX_TransportRoutes_RouteCode ON dbo.TransportRoutes (RouteCode);';

    IF COL_LENGTH(N'dbo.RoutePoints', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RoutePoints', N'PointOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RoutePoints') AND name = N'IX_RoutePoints_Route')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RoutePoints_Route ON dbo.RoutePoints (TransportRouteId, PointOrder);';

    IF COL_LENGTH(N'dbo.RoutePoints', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RoutePoints', N'PointOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RoutePoints') AND name = N'UQ_RoutePoints_RouteAndOrder')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_RoutePoints_RouteAndOrder ON dbo.RoutePoints (TransportRouteId, PointOrder);';

    IF COL_LENGTH(N'dbo.RouteWaypoints', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteWaypoints', N'WaypointOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteWaypoints') AND name = N'UQ_RouteWaypoints_RouteAndOrder')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_RouteWaypoints_RouteAndOrder ON dbo.RouteWaypoints (TransportRouteId, WaypointOrder);';

    IF COL_LENGTH(N'dbo.RouteStops', N'TransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteStops', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteStops') AND name = N'IX_RouteStops_Stop')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RouteStops_Stop ON dbo.RouteStops (TransportStopId, TransportRouteId);';

    IF COL_LENGTH(N'dbo.RouteStops', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteStops', N'StopOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteStops') AND name = N'UQ_RouteStops_RouteAndOrder')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_RouteStops_RouteAndOrder ON dbo.RouteStops (TransportRouteId, StopOrder);';

    IF COL_LENGTH(N'dbo.RouteStops', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteStops') AND name = N'UQ_RouteStops_RouteAndStop')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_RouteStops_RouteAndStop ON dbo.RouteStops (TransportRouteId, TransportStopId);';

    IF COL_LENGTH(N'dbo.RouteSegments', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteSegments', N'SegmentOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteSegments') AND name = N'UQ_RouteSegments_RouteAndOrder')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_RouteSegments_RouteAndOrder ON dbo.RouteSegments (TransportRouteId, SegmentOrder);';

    IF COL_LENGTH(N'dbo.RouteSegments', N'FromRouteStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteSegments') AND name = N'IX_RouteSegments_FromRouteStop')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RouteSegments_FromRouteStop ON dbo.RouteSegments (FromRouteStopId);';

    IF COL_LENGTH(N'dbo.RouteSegments', N'ToRouteStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteSegments') AND name = N'IX_RouteSegments_ToRouteStop')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RouteSegments_ToRouteStop ON dbo.RouteSegments (ToRouteStopId);';

    IF COL_LENGTH(N'dbo.FareRules', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.FareRules', N'PassengerType') IS NOT NULL
       AND COL_LENGTH(N'dbo.FareRules', N'EffectiveFrom') IS NOT NULL
       AND COL_LENGTH(N'dbo.FareRules', N'EffectiveUntil') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FareRules') AND name = N'IX_FareRules_RouteAndEffectiveDate')
        EXEC sys.sp_executesql N'CREATE INDEX IX_FareRules_RouteAndEffectiveDate ON dbo.FareRules (TransportRouteId, PassengerType, EffectiveFrom, EffectiveUntil);';

    IF COL_LENGTH(N'dbo.FareRules', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FareRules') AND name = N'IX_FareRules_TransportMode')
        EXEC sys.sp_executesql N'CREATE INDEX IX_FareRules_TransportMode ON dbo.FareRules (TransportModeId);';

    IF COL_LENGTH(N'dbo.TricyclePoints', N'CenterLatitude') IS NOT NULL
       AND COL_LENGTH(N'dbo.TricyclePoints', N'CenterLongitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TricyclePoints') AND name = N'IX_TricyclePoints_Coordinates')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TricyclePoints_Coordinates ON dbo.TricyclePoints (CenterLatitude, CenterLongitude);';

    IF COL_LENGTH(N'dbo.TricyclePoints', N'PointCode') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TricyclePoints') AND name = N'UX_TricyclePoints_PointCode')
        EXEC sys.sp_executesql N'
            IF NOT EXISTS (SELECT PointCode FROM dbo.TricyclePoints GROUP BY PointCode HAVING COUNT_BIG(*) > 1)
                CREATE UNIQUE INDEX UX_TricyclePoints_PointCode ON dbo.TricyclePoints (PointCode);';

    IF COL_LENGTH(N'dbo.TricyclePoints', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TricyclePoints') AND name = N'UX_TricyclePoints_TransportStop')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_TricyclePoints_TransportStop ON dbo.TricyclePoints (TransportStopId) WHERE TransportStopId IS NOT NULL;';

    IF COL_LENGTH(N'dbo.TransferConnections', N'FromTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransferConnections', N'ToTransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TransferConnections') AND name = N'UQ_TransferConnections_FromAndTo')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_TransferConnections_FromAndTo ON dbo.TransferConnections (FromTransportStopId, ToTransportStopId);';

    IF COL_LENGTH(N'dbo.Drivers', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.Drivers') AND name = N'UQ_Drivers_UserId')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UQ_Drivers_UserId ON dbo.Drivers (UserId);';

    IF COL_LENGTH(N'dbo.Drivers', N'LicenseNumber') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.Drivers') AND name = N'UX_Drivers_LicenseNumber')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_Drivers_LicenseNumber ON dbo.Drivers (LicenseNumber) WHERE LicenseNumber IS NOT NULL;';

    IF COL_LENGTH(N'dbo.DriverVehicles', N'PlateNumber') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverVehicles') AND name = N'UX_DriverVehicles_PlateNumber')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_DriverVehicles_PlateNumber ON dbo.DriverVehicles (PlateNumber) WHERE PlateNumber IS NOT NULL;';

    IF COL_LENGTH(N'dbo.DriverVehicles', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverVehicles', N'PlateNumber') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverVehicles') AND name = N'UX_DriverVehicles_DriverAndPlate')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_DriverVehicles_DriverAndPlate ON dbo.DriverVehicles (DriverId, PlateNumber) WHERE PlateNumber IS NOT NULL;';

    IF COL_LENGTH(N'dbo.DriverVehicles', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverVehicles') AND name = N'IX_DriverVehicles_TransportMode')
        EXEC sys.sp_executesql N'CREATE INDEX IX_DriverVehicles_TransportMode ON dbo.DriverVehicles (TransportModeId);';

    IF COL_LENGTH(N'dbo.DriverLocations', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverLocations') AND name = N'UX_DriverLocations_Driver')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_DriverLocations_Driver ON dbo.DriverLocations (DriverId);';

    IF COL_LENGTH(N'dbo.DriverLocations', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverLocations', N'RecordedAt') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverLocations') AND name = N'IX_DriverLocations_DriverAndRecordedAt')
        EXEC sys.sp_executesql N'CREATE INDEX IX_DriverLocations_DriverAndRecordedAt ON dbo.DriverLocations (DriverId ASC, RecordedAt DESC);';

    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverAvailabilitySessions') AND name = N'IX_DriverAvailability_Driver')
        EXEC sys.sp_executesql N'CREATE INDEX IX_DriverAvailability_Driver ON dbo.DriverAvailabilitySessions (DriverId);';

    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'TricyclePointId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'Status') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverAvailabilitySessions') AND name = N'IX_DriverAvailability_PointAndStatus')
        EXEC sys.sp_executesql N'CREATE INDEX IX_DriverAvailability_PointAndStatus ON dbo.DriverAvailabilitySessions (TricyclePointId, Status);';

    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'Status') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'EndedAt') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.DriverAvailabilitySessions') AND name = N'IX_DriverAvailability_DriverAndStatus')
        EXEC sys.sp_executesql N'CREATE INDEX IX_DriverAvailability_DriverAndStatus ON dbo.DriverAvailabilitySessions (DriverId, Status, EndedAt);';

    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'Status') IS NOT NULL
       AND COL_LENGTH(N'dbo.PassengerRideRequests', N'RequestedAt') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PassengerRideRequests') AND name = N'IX_PassengerRideRequests_Status')
        EXEC sys.sp_executesql N'CREATE INDEX IX_PassengerRideRequests_Status ON dbo.PassengerRideRequests (Status, RequestedAt);';

    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'PassengerUserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PassengerRideRequests') AND name = N'IX_PassengerRideRequests_Passenger')
        EXEC sys.sp_executesql N'CREATE INDEX IX_PassengerRideRequests_Passenger ON dbo.PassengerRideRequests (PassengerUserId);';

    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PassengerRideRequests') AND name = N'IX_PassengerRideRequests_TransportMode')
        EXEC sys.sp_executesql N'CREATE INDEX IX_PassengerRideRequests_TransportMode ON dbo.PassengerRideRequests (TransportModeId);';

    IF COL_LENGTH(N'dbo.RideMatches', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RideMatches', N'Status') IS NOT NULL
       AND COL_LENGTH(N'dbo.RideMatches', N'MatchedAt') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RideMatches') AND name = N'IX_RideMatches_DriverAndStatus')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RideMatches_DriverAndStatus ON dbo.RideMatches (DriverId, Status, MatchedAt);';

    IF COL_LENGTH(N'dbo.RideMatches', N'PassengerRideRequestId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RideMatches') AND name = N'IX_RideMatches_Request')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RideMatches_Request ON dbo.RideMatches (PassengerRideRequestId);';

    IF COL_LENGTH(N'dbo.RideMatches', N'PassengerRideRequestId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RideMatches', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RideMatches', N'SessionId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RideMatches') AND name = N'UX_RideMatches_RequestDriverSession')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_RideMatches_RequestDriverSession ON dbo.RideMatches (PassengerRideRequestId, DriverId, SessionId) WHERE SessionId IS NOT NULL;';

    IF COL_LENGTH(N'dbo.TripSearches', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TripSearches') AND name = N'IX_TripSearches_User')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TripSearches_User ON dbo.TripSearches (UserId);';

    IF COL_LENGTH(N'dbo.RouteRecommendations', N'TripSearchId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteRecommendations') AND name = N'IX_RouteRecommendations_TripSearch')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RouteRecommendations_TripSearch ON dbo.RouteRecommendations (TripSearchId);';

    IF COL_LENGTH(N'dbo.RouteRecommendations', N'TripSearchId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteRecommendations', N'RecommendationType') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteRecommendations', N'RankNumber') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RouteRecommendations') AND name = N'UX_RouteRecommendations_SearchTypeRank')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_RouteRecommendations_SearchTypeRank ON dbo.RouteRecommendations (TripSearchId, RecommendationType, RankNumber);';

    IF COL_LENGTH(N'dbo.RecommendationLegs', N'RecommendationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RecommendationLegs', N'LegOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RecommendationLegs') AND name = N'IX_RecommendationLegs_Recommendation')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RecommendationLegs_Recommendation ON dbo.RecommendationLegs (RecommendationId, LegOrder);';

    IF COL_LENGTH(N'dbo.RecommendationLegs', N'RecommendationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RecommendationLegs', N'LegOrder') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RecommendationLegs') AND name = N'UX_RecommendationLegs_RecommendationOrder')
        EXEC sys.sp_executesql N'CREATE UNIQUE INDEX UX_RecommendationLegs_RecommendationOrder ON dbo.RecommendationLegs (RecommendationId, LegOrder);';

    IF COL_LENGTH(N'dbo.RecommendationLegs', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RecommendationLegs') AND name = N'IX_RecommendationLegs_TransportMode')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RecommendationLegs_TransportMode ON dbo.RecommendationLegs (TransportModeId);';

    IF COL_LENGTH(N'dbo.RecommendationLegs', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RecommendationLegs') AND name = N'IX_RecommendationLegs_Route')
        EXEC sys.sp_executesql N'CREATE INDEX IX_RecommendationLegs_Route ON dbo.RecommendationLegs (TransportRouteId) WHERE TransportRouteId IS NOT NULL;';

    IF COL_LENGTH(N'dbo.PassengerTrips', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PassengerTrips') AND name = N'IX_PassengerTrips_User')
        EXEC sys.sp_executesql N'CREATE INDEX IX_PassengerTrips_User ON dbo.PassengerTrips (UserId);';

    IF COL_LENGTH(N'dbo.TripAlerts', N'PassengerTripId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TripAlerts') AND name = N'IX_TripAlerts_PassengerTrip')
        EXEC sys.sp_executesql N'CREATE INDEX IX_TripAlerts_PassengerTrip ON dbo.TripAlerts (PassengerTripId);';

    IF COL_LENGTH(N'dbo.ChatConversations', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ChatConversations') AND name = N'IX_ChatConversations_User')
        EXEC sys.sp_executesql N'CREATE INDEX IX_ChatConversations_User ON dbo.ChatConversations (UserId);';

    IF COL_LENGTH(N'dbo.ChatMessages', N'ConversationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.ChatMessages', N'CreatedAt') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ChatMessages') AND name = N'IX_ChatMessages_Conversation')
        EXEC sys.sp_executesql N'CREATE INDEX IX_ChatMessages_Conversation ON dbo.ChatMessages (ConversationId, CreatedAt);';

    IF COL_LENGTH(N'dbo.TransportStops', N'Latitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TransportStops_Latitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransportStops WITH NOCHECK ADD CONSTRAINT CK_TransportStops_Latitude CHECK (Latitude BETWEEN -90 AND 90);';
    IF COL_LENGTH(N'dbo.TransportStops', N'Longitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TransportStops_Longitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransportStops WITH NOCHECK ADD CONSTRAINT CK_TransportStops_Longitude CHECK (Longitude BETWEEN -180 AND 180);';
    IF COL_LENGTH(N'dbo.RoutePoints', N'Latitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_RoutePoints_Latitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RoutePoints WITH NOCHECK ADD CONSTRAINT CK_RoutePoints_Latitude CHECK (Latitude BETWEEN -90 AND 90);';
    IF COL_LENGTH(N'dbo.RoutePoints', N'Longitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_RoutePoints_Longitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RoutePoints WITH NOCHECK ADD CONSTRAINT CK_RoutePoints_Longitude CHECK (Longitude BETWEEN -180 AND 180);';
    IF COL_LENGTH(N'dbo.TricyclePoints', N'CenterLatitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TricyclePoints_Latitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TricyclePoints WITH NOCHECK ADD CONSTRAINT CK_TricyclePoints_Latitude CHECK (CenterLatitude BETWEEN -90 AND 90);';
    IF COL_LENGTH(N'dbo.TricyclePoints', N'CenterLongitude') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TricyclePoints_Longitude')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TricyclePoints WITH NOCHECK ADD CONSTRAINT CK_TricyclePoints_Longitude CHECK (CenterLongitude BETWEEN -180 AND 180);';
    IF COL_LENGTH(N'dbo.TricyclePoints', N'RadiusMeters') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TricyclePoints_RadiusMeters')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TricyclePoints WITH NOCHECK ADD CONSTRAINT CK_TricyclePoints_RadiusMeters CHECK (RadiusMeters > 0);';
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'AvailableSeats') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_DriverAvailability_AvailableSeats')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverAvailabilitySessions WITH NOCHECK ADD CONSTRAINT CK_DriverAvailability_AvailableSeats CHECK (AvailableSeats > 0);';
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'PassengerCount') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_PassengerRideRequests_PassengerCount')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerRideRequests WITH NOCHECK ADD CONSTRAINT CK_PassengerRideRequests_PassengerCount CHECK (PassengerCount > 0);';
    IF COL_LENGTH(N'dbo.TripSearches', N'PassengerCount') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_TripSearches_PassengerCount')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TripSearches WITH NOCHECK ADD CONSTRAINT CK_TripSearches_PassengerCount CHECK (PassengerCount > 0);';

    IF COL_LENGTH(N'dbo.TransportRoutes', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportModes', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TransportRoutes_TransportModes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransportRoutes WITH NOCHECK ADD CONSTRAINT FK_TransportRoutes_TransportModes FOREIGN KEY (TransportModeId) REFERENCES dbo.TransportModes (TransportModeId);';
    IF COL_LENGTH(N'dbo.TransportRoutes', N'StartTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TransportRoutes_StartStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransportRoutes WITH NOCHECK ADD CONSTRAINT FK_TransportRoutes_StartStop FOREIGN KEY (StartTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.TransportRoutes', N'EndTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TransportRoutes_EndStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransportRoutes WITH NOCHECK ADD CONSTRAINT FK_TransportRoutes_EndStop FOREIGN KEY (EndTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.RoutePoints', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RoutePoints_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RoutePoints WITH NOCHECK ADD CONSTRAINT FK_RoutePoints_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId);';
    IF COL_LENGTH(N'dbo.RouteWaypoints', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteWaypoints_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteWaypoints WITH NOCHECK ADD CONSTRAINT FK_RouteWaypoints_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId) ON DELETE CASCADE;';
    IF COL_LENGTH(N'dbo.RouteStops', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteStops_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteStops WITH NOCHECK ADD CONSTRAINT FK_RouteStops_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId);';
    IF COL_LENGTH(N'dbo.RouteStops', N'TransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteStops_TransportStops')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteStops WITH NOCHECK ADD CONSTRAINT FK_RouteStops_TransportStops FOREIGN KEY (TransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.RouteSegments', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteSegments_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteSegments WITH NOCHECK ADD CONSTRAINT FK_RouteSegments_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId);';
    IF COL_LENGTH(N'dbo.RouteSegments', N'FromRouteStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteStops', N'RouteStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteSegments_FromRouteStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteSegments WITH NOCHECK ADD CONSTRAINT FK_RouteSegments_FromRouteStop FOREIGN KEY (FromRouteStopId) REFERENCES dbo.RouteStops (RouteStopId);';
    IF COL_LENGTH(N'dbo.RouteSegments', N'ToRouteStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteStops', N'RouteStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteSegments_ToRouteStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteSegments WITH NOCHECK ADD CONSTRAINT FK_RouteSegments_ToRouteStop FOREIGN KEY (ToRouteStopId) REFERENCES dbo.RouteStops (RouteStopId);';
    IF COL_LENGTH(N'dbo.FareRules', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FareRules_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.FareRules WITH NOCHECK ADD CONSTRAINT FK_FareRules_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId);';
    IF COL_LENGTH(N'dbo.FareRules', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportModes', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FareRules_TransportModes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.FareRules WITH NOCHECK ADD CONSTRAINT FK_FareRules_TransportModes FOREIGN KEY (TransportModeId) REFERENCES dbo.TransportModes (TransportModeId);';
    IF COL_LENGTH(N'dbo.TricyclePoints', N'TransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TricyclePoints_TransportStops')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TricyclePoints WITH NOCHECK ADD CONSTRAINT FK_TricyclePoints_TransportStops FOREIGN KEY (TransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.TransferConnections', N'FromTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TransferConnections_FromStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransferConnections WITH NOCHECK ADD CONSTRAINT FK_TransferConnections_FromStop FOREIGN KEY (FromTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.TransferConnections', N'ToTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TransferConnections_ToStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TransferConnections WITH NOCHECK ADD CONSTRAINT FK_TransferConnections_ToStop FOREIGN KEY (ToTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.Drivers', N'UserId') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_Drivers_UserProfiles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.Drivers WITH NOCHECK ADD CONSTRAINT FK_Drivers_UserProfiles FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles (UserId);';
    IF COL_LENGTH(N'dbo.Drivers', N'HomeTerminalId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_Drivers_HomeTerminal')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.Drivers WITH NOCHECK ADD CONSTRAINT FK_Drivers_HomeTerminal FOREIGN KEY (HomeTerminalId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.DriverVehicles', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.Drivers', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverVehicles_Drivers')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverVehicles WITH NOCHECK ADD CONSTRAINT FK_DriverVehicles_Drivers FOREIGN KEY (DriverId) REFERENCES dbo.Drivers (DriverId);';
    IF COL_LENGTH(N'dbo.DriverVehicles', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportModes', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverVehicles_TransportModes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverVehicles WITH NOCHECK ADD CONSTRAINT FK_DriverVehicles_TransportModes FOREIGN KEY (TransportModeId) REFERENCES dbo.TransportModes (TransportModeId);';
    IF COL_LENGTH(N'dbo.DriverVehicles', N'TricyclePointId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TricyclePoints', N'TricyclePointId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverVehicles_TricyclePoints')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverVehicles WITH NOCHECK ADD CONSTRAINT FK_DriverVehicles_TricyclePoints FOREIGN KEY (TricyclePointId) REFERENCES dbo.TricyclePoints (TricyclePointId);';
    IF COL_LENGTH(N'dbo.DriverLocations', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.Drivers', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverLocations_Drivers')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverLocations WITH NOCHECK ADD CONSTRAINT FK_DriverLocations_Drivers FOREIGN KEY (DriverId) REFERENCES dbo.Drivers (DriverId);';
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.Drivers', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverAvailability_Drivers')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverAvailabilitySessions WITH NOCHECK ADD CONSTRAINT FK_DriverAvailability_Drivers FOREIGN KEY (DriverId) REFERENCES dbo.Drivers (DriverId);';
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DriverVehicleId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverVehicles', N'DriverVehicleId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverAvailability_Vehicles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverAvailabilitySessions WITH NOCHECK ADD CONSTRAINT FK_DriverAvailability_Vehicles FOREIGN KEY (DriverVehicleId) REFERENCES dbo.DriverVehicles (DriverVehicleId);';
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DestinationStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverAvailability_DestinationStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverAvailabilitySessions WITH NOCHECK ADD CONSTRAINT FK_DriverAvailability_DestinationStop FOREIGN KEY (DestinationStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'TricyclePointId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TricyclePoints', N'TricyclePointId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_DriverAvailability_TricyclePoints')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.DriverAvailabilitySessions WITH NOCHECK ADD CONSTRAINT FK_DriverAvailability_TricyclePoints FOREIGN KEY (TricyclePointId) REFERENCES dbo.TricyclePoints (TricyclePointId);';
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'PassengerUserId') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideRequests_UserProfiles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerRideRequests WITH NOCHECK ADD CONSTRAINT FK_RideRequests_UserProfiles FOREIGN KEY (PassengerUserId) REFERENCES dbo.UserProfiles (UserId);';
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportModes', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideRequests_TransportModes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerRideRequests WITH NOCHECK ADD CONSTRAINT FK_RideRequests_TransportModes FOREIGN KEY (TransportModeId) REFERENCES dbo.TransportModes (TransportModeId);';
    IF COL_LENGTH(N'dbo.PassengerRideRequests', N'TricyclePointId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TricyclePoints', N'TricyclePointId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideRequests_TricyclePoints')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerRideRequests WITH NOCHECK ADD CONSTRAINT FK_RideRequests_TricyclePoints FOREIGN KEY (TricyclePointId) REFERENCES dbo.TricyclePoints (TricyclePointId);';
    IF COL_LENGTH(N'dbo.RideMatches', N'DriverId') IS NOT NULL
       AND COL_LENGTH(N'dbo.Drivers', N'DriverId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideMatches_Drivers')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RideMatches WITH NOCHECK ADD CONSTRAINT FK_RideMatches_Drivers FOREIGN KEY (DriverId) REFERENCES dbo.Drivers (DriverId);';
    IF COL_LENGTH(N'dbo.RideMatches', N'DriverVehicleId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverVehicles', N'DriverVehicleId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideMatches_Vehicles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RideMatches WITH NOCHECK ADD CONSTRAINT FK_RideMatches_Vehicles FOREIGN KEY (DriverVehicleId) REFERENCES dbo.DriverVehicles (DriverVehicleId);';
    IF COL_LENGTH(N'dbo.RideMatches', N'PassengerRideRequestId') IS NOT NULL
       AND COL_LENGTH(N'dbo.PassengerRideRequests', N'PassengerRideRequestId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideMatches_RideRequests')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RideMatches WITH NOCHECK ADD CONSTRAINT FK_RideMatches_RideRequests FOREIGN KEY (PassengerRideRequestId) REFERENCES dbo.PassengerRideRequests (PassengerRideRequestId);';
    IF COL_LENGTH(N'dbo.RideMatches', N'SessionId') IS NOT NULL
       AND COL_LENGTH(N'dbo.DriverAvailabilitySessions', N'DriverAvailabilitySessionId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RideMatches_AvailabilitySessions')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RideMatches WITH NOCHECK ADD CONSTRAINT FK_RideMatches_AvailabilitySessions FOREIGN KEY (SessionId) REFERENCES dbo.DriverAvailabilitySessions (DriverAvailabilitySessionId);';
    IF COL_LENGTH(N'dbo.TripSearches', N'UserId') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TripSearches_UserProfiles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TripSearches WITH NOCHECK ADD CONSTRAINT FK_TripSearches_UserProfiles FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles (UserId);';
    IF COL_LENGTH(N'dbo.RouteRecommendations', N'TripSearchId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TripSearches', N'TripSearchId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RouteRecommendations_TripSearches')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RouteRecommendations WITH NOCHECK ADD CONSTRAINT FK_RouteRecommendations_TripSearches FOREIGN KEY (TripSearchId) REFERENCES dbo.TripSearches (TripSearchId);';
    IF COL_LENGTH(N'dbo.RecommendationLegs', N'RecommendationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteRecommendations', N'RecommendationId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RecommendationLegs_RouteRecommendations')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RecommendationLegs WITH NOCHECK ADD CONSTRAINT FK_RecommendationLegs_RouteRecommendations FOREIGN KEY (RecommendationId) REFERENCES dbo.RouteRecommendations (RecommendationId);';
    IF COL_LENGTH(N'dbo.RecommendationLegs', N'TransportModeId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportModes', N'TransportModeId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RecommendationLegs_TransportModes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RecommendationLegs WITH NOCHECK ADD CONSTRAINT FK_RecommendationLegs_TransportModes FOREIGN KEY (TransportModeId) REFERENCES dbo.TransportModes (TransportModeId);';
    IF COL_LENGTH(N'dbo.RecommendationLegs', N'TransportRouteId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportRoutes', N'TransportRouteId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RecommendationLegs_TransportRoutes')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RecommendationLegs WITH NOCHECK ADD CONSTRAINT FK_RecommendationLegs_TransportRoutes FOREIGN KEY (TransportRouteId) REFERENCES dbo.TransportRoutes (TransportRouteId);';
    IF COL_LENGTH(N'dbo.RecommendationLegs', N'FromTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RecommendationLegs_FromStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RecommendationLegs WITH NOCHECK ADD CONSTRAINT FK_RecommendationLegs_FromStop FOREIGN KEY (FromTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.RecommendationLegs', N'ToTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RecommendationLegs_ToStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.RecommendationLegs WITH NOCHECK ADD CONSTRAINT FK_RecommendationLegs_ToStop FOREIGN KEY (ToTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.PassengerTrips', N'UserId') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PassengerTrips_UserProfiles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerTrips WITH NOCHECK ADD CONSTRAINT FK_PassengerTrips_UserProfiles FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles (UserId);';
    IF COL_LENGTH(N'dbo.PassengerTrips', N'RecommendationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RouteRecommendations', N'RecommendationId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PassengerTrips_RouteRecommendations')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.PassengerTrips WITH NOCHECK ADD CONSTRAINT FK_PassengerTrips_RouteRecommendations FOREIGN KEY (RecommendationId) REFERENCES dbo.RouteRecommendations (RecommendationId);';
    IF COL_LENGTH(N'dbo.TripAlerts', N'PassengerTripId') IS NOT NULL
       AND COL_LENGTH(N'dbo.PassengerTrips', N'PassengerTripId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TripAlerts_PassengerTrips')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TripAlerts WITH NOCHECK ADD CONSTRAINT FK_TripAlerts_PassengerTrips FOREIGN KEY (PassengerTripId) REFERENCES dbo.PassengerTrips (PassengerTripId);';
    IF COL_LENGTH(N'dbo.TripAlerts', N'LegId') IS NOT NULL
       AND COL_LENGTH(N'dbo.RecommendationLegs', N'LegId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TripAlerts_RecommendationLegs')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TripAlerts WITH NOCHECK ADD CONSTRAINT FK_TripAlerts_RecommendationLegs FOREIGN KEY (LegId) REFERENCES dbo.RecommendationLegs (LegId);';
    IF COL_LENGTH(N'dbo.TripAlerts', N'TargetTransportStopId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TransportStops', N'TransportStopId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TripAlerts_TargetStop')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.TripAlerts WITH NOCHECK ADD CONSTRAINT FK_TripAlerts_TargetStop FOREIGN KEY (TargetTransportStopId) REFERENCES dbo.TransportStops (TransportStopId);';
    IF COL_LENGTH(N'dbo.ChatConversations', N'UserId') IS NOT NULL
       AND COL_LENGTH(N'dbo.UserProfiles', N'UserId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ChatConversations_UserProfiles')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.ChatConversations WITH NOCHECK ADD CONSTRAINT FK_ChatConversations_UserProfiles FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles (UserId);';
    IF COL_LENGTH(N'dbo.ChatMessages', N'ConversationId') IS NOT NULL
       AND COL_LENGTH(N'dbo.ChatConversations', N'ConversationId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ChatMessages_ChatConversations')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.ChatMessages WITH NOCHECK ADD CONSTRAINT FK_ChatMessages_ChatConversations FOREIGN KEY (ConversationId) REFERENCES dbo.ChatConversations (ConversationId);';
    IF COL_LENGTH(N'dbo.ChatMessages', N'TripSearchId') IS NOT NULL
       AND COL_LENGTH(N'dbo.TripSearches', N'TripSearchId') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ChatMessages_TripSearches')
        EXEC sys.sp_executesql N'ALTER TABLE dbo.ChatMessages WITH NOCHECK ADD CONSTRAINT FK_ChatMessages_TripSearches FOREIGN KEY (TripSearchId) REFERENCES dbo.TripSearches (TripSearchId);';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
    BEGIN
        ROLLBACK TRANSACTION;
    END;

    THROW;
END CATCH;

GO

-- ── Part 2: TukiNavigationSchema.sql (Phase 2-6 navigation tables) ──────────

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.TripSessions', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TripSessions
        (
            TripSessionId uniqueidentifier NOT NULL CONSTRAINT DF_TripSessions_Id DEFAULT (newsequentialid()),
            UserId uniqueidentifier NOT NULL,
            RecommendationId uniqueidentifier NOT NULL,
            OriginLatitude float NOT NULL,
            OriginLongitude float NOT NULL,
            DestinationLatitude float NOT NULL,
            DestinationLongitude float NOT NULL,
            DestinationName nvarchar(250) NULL,
            CurrentLegIndex int NOT NULL CONSTRAINT DF_TripSessions_CurrentLeg DEFAULT (0),
            CurrentNavigationState nvarchar(40) NOT NULL,
            CurrentProgressMeters float NOT NULL CONSTRAINT DF_TripSessions_Progress DEFAULT (0),
            CurrentRouteProgressMeters float NULL,
            StartedAt datetime2(7) NULL,
            LastLocationAt datetime2(7) NULL,
            LastLatitude float NULL,
            LastLongitude float NULL,
            LastAccuracyMeters float NULL,
            ConsecutiveStateConfirmationSamples int NOT NULL CONSTRAINT DF_TripSessions_StateSamples DEFAULT (0),
            ConsecutiveOffRouteSamples int NOT NULL CONSTRAINT DF_TripSessions_OffRouteSamples DEFAULT (0),
            OffRouteSuspectedAt datetime2(7) NULL,
            LastRerouteReason nvarchar(50) NULL,
            LastNavigationStatus nvarchar(50) NULL,
            LastSpeechEventKey nvarchar(250) NULL,
            LastSpokenInstruction nvarchar(500) NULL,
            CompletedAt datetime2(7) NULL,
            CancelledAt datetime2(7) NULL,
            OriginalBudget decimal(10,2) NULL,
            OriginalPreference nvarchar(30) NULL,
            LastRerouteAt datetime2(7) NULL,
            RerouteCount int NOT NULL CONSTRAINT DF_TripSessions_RerouteCount DEFAULT (0),
            CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_TripSessions_CreatedAt DEFAULT (sysutcdatetime()),
            UpdatedAt datetime2(7) NOT NULL CONSTRAINT DF_TripSessions_UpdatedAt DEFAULT (sysutcdatetime()),
            CONSTRAINT PK_TripSessions PRIMARY KEY (TripSessionId),
            CONSTRAINT FK_TripSessions_UserProfiles FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles (UserId),
            CONSTRAINT FK_TripSessions_RouteRecommendations FOREIGN KEY (RecommendationId) REFERENCES dbo.RouteRecommendations (RecommendationId)
        );
        CREATE INDEX IX_TripSessions_User_State ON dbo.TripSessions (UserId, CurrentNavigationState);
        CREATE INDEX IX_TripSessions_Recommendation ON dbo.TripSessions (RecommendationId);
    END;

    IF OBJECT_ID(N'dbo.NavigationInstructions', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.NavigationInstructions
        (
            NavigationInstructionId uniqueidentifier NOT NULL CONSTRAINT DF_NavigationInstructions_Id DEFAULT (newsequentialid()),
            TripSessionId uniqueidentifier NOT NULL,
            Sequence int NOT NULL,
            Type nvarchar(40) NOT NULL,
            Audience nvarchar(20) NOT NULL,
            LegIndex int NOT NULL,
            [Text] nvarchar(500) NOT NULL,
            StreetName nvarchar(250) NULL,
            SourceManeuverType int NULL,
            BeginShapeIndex int NULL,
            EndShapeIndex int NULL,
            Latitude float NULL,
            Longitude float NULL,
            DistanceFromLegStartMeters float NULL,
            DistanceFromRouteStartMeters float NULL,
            TriggerDistanceMeters float NOT NULL,
            RequiresConfirmation bit NOT NULL,
            CONSTRAINT PK_NavigationInstructions PRIMARY KEY (NavigationInstructionId),
            CONSTRAINT FK_NavigationInstructions_TripSessions FOREIGN KEY (TripSessionId)
                REFERENCES dbo.TripSessions (TripSessionId) ON DELETE CASCADE
        );
        CREATE UNIQUE INDEX UX_NavigationInstructions_SessionSequence
            ON dbo.NavigationInstructions (TripSessionId, Sequence);
    END;

    IF OBJECT_ID(N'dbo.TripLandmarkCandidates', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TripLandmarkCandidates
        (
            TripLandmarkCandidateId uniqueidentifier NOT NULL CONSTRAINT DF_TripLandmarkCandidates_Id DEFAULT (newsequentialid()),
            TripSessionId uniqueidentifier NOT NULL,
            LegIndex int NOT NULL,
            ExternalPlaceId nvarchar(250) NOT NULL,
            Name nvarchar(200) NOT NULL,
            Category nvarchar(50) NOT NULL,
            [Role] nvarchar(30) NOT NULL CONSTRAINT DF_TripLandmarkCandidates_Role DEFAULT ('ProgressReference'),
            Relation nvarchar(30) NOT NULL CONSTRAINT DF_TripLandmarkCandidates_Relation DEFAULT ('AlongRoute'),
            Latitude float NOT NULL,
            Longitude float NOT NULL,
            DistanceFromRouteStartMeters float NOT NULL,
            DistanceFromTargetMeters float NOT NULL CONSTRAINT DF_TripLandmarkCandidates_TargetDistance DEFAULT (0),
            TriggerBeforeMeters float NOT NULL,
            TriggerAfterMeters float NOT NULL,
            CachedAt datetime2(7) NOT NULL CONSTRAINT DF_TripLandmarkCandidates_CachedAt DEFAULT (sysutcdatetime()),
            TriggeredAt datetime2(7) NULL,
            CONSTRAINT PK_TripLandmarkCandidates PRIMARY KEY (TripLandmarkCandidateId),
            CONSTRAINT FK_TripLandmarkCandidates_TripSessions FOREIGN KEY (TripSessionId)
                REFERENCES dbo.TripSessions (TripSessionId) ON DELETE CASCADE
        );
        CREATE INDEX IX_TripLandmarkCandidates_SessionLegProgress
            ON dbo.TripLandmarkCandidates (TripSessionId, LegIndex, DistanceFromRouteStartMeters);
        CREATE UNIQUE INDEX UX_TripLandmarkCandidates_SessionLegPlace
            ON dbo.TripLandmarkCandidates (TripSessionId, LegIndex, ExternalPlaceId);
    END;

    IF COL_LENGTH(N'dbo.TripSessions', N'LastSpeechEventKey') IS NULL
        ALTER TABLE dbo.TripSessions ADD LastSpeechEventKey nvarchar(250) NULL;
    IF COL_LENGTH(N'dbo.TripSessions', N'LastSpokenInstruction') IS NULL
        ALTER TABLE dbo.TripSessions ADD LastSpokenInstruction nvarchar(500) NULL;
    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Role') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates ADD [Role] nvarchar(30) NOT NULL
            CONSTRAINT DF_TripLandmarkCandidates_Role_Upgrade DEFAULT ('ProgressReference');
    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Relation') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates ADD Relation nvarchar(30) NOT NULL
            CONSTRAINT DF_TripLandmarkCandidates_Relation_Upgrade DEFAULT ('AlongRoute');
    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'DistanceFromTargetMeters') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates ADD DistanceFromTargetMeters float NOT NULL
            CONSTRAINT DF_TripLandmarkCandidates_TargetDistance_Upgrade DEFAULT (0);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

GO

-- ── Part 3: migrations/20260819_LocalUserAuthentication.sql ─────────────────

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.LocalUserCredentials', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LocalUserCredentials
    (
        UserId UNIQUEIDENTIFIER NOT NULL,
        PasswordHash NVARCHAR(512) NOT NULL,
        CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_LocalUserCredentials_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_LocalUserCredentials_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_LocalUserCredentials PRIMARY KEY (UserId),
        CONSTRAINT FK_LocalUserCredentials_UserProfiles
            FOREIGN KEY (UserId) REFERENCES dbo.UserProfiles(UserId) ON DELETE CASCADE
    );
END;

COMMIT TRANSACTION;

GO

-- ── Part 4: migrations/20260819_NavigationSpeechAndSemanticLandmarks.sql ────

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.TripSessions', N'U') IS NULL
        THROW 50001, 'dbo.TripSessions does not exist. Run TukiNavigationSchema.sql first.', 1;

    IF OBJECT_ID(N'dbo.TripLandmarkCandidates', N'U') IS NULL
        THROW 50002, 'dbo.TripLandmarkCandidates does not exist. Run TukiNavigationSchema.sql first.', 1;

    IF COL_LENGTH(N'dbo.TripSessions', N'LastSpeechEventKey') IS NULL
        ALTER TABLE dbo.TripSessions
            ADD LastSpeechEventKey nvarchar(250) NULL;

    IF COL_LENGTH(N'dbo.TripSessions', N'LastSpokenInstruction') IS NULL
        ALTER TABLE dbo.TripSessions
            ADD LastSpokenInstruction nvarchar(500) NULL;

    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Role') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates
            ADD [Role] nvarchar(30) NOT NULL
                CONSTRAINT DF_TripLandmarkCandidates_Role_20260819
                DEFAULT ('ProgressReference');

    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Relation') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates
            ADD Relation nvarchar(30) NOT NULL
                CONSTRAINT DF_TripLandmarkCandidates_Relation_20260819
                DEFAULT ('AlongRoute');

    IF COL_LENGTH(N'dbo.TripLandmarkCandidates', N'DistanceFromTargetMeters') IS NULL
        ALTER TABLE dbo.TripLandmarkCandidates
            ADD DistanceFromTargetMeters float NOT NULL
                CONSTRAINT DF_TripLandmarkCandidates_TargetDistance_20260819
                DEFAULT (0);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT
    COL_LENGTH(N'dbo.TripSessions', N'LastSpeechEventKey') AS LastSpeechEventKeyBytes,
    COL_LENGTH(N'dbo.TripSessions', N'LastSpokenInstruction') AS LastSpokenInstructionBytes,
    COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Role') AS LandmarkRoleBytes,
    COL_LENGTH(N'dbo.TripLandmarkCandidates', N'Relation') AS LandmarkRelationBytes,
    COL_LENGTH(N'dbo.TripLandmarkCandidates', N'DistanceFromTargetMeters') AS LandmarkTargetDistanceBytes;
