[tuki_gcp]
gcp ansible_host=34.2.156.136 ansible_user=tuki-gcp ansible_ssh_private_key_file=/home/mark/.ssh/tuki_gcp

[tuki_azure]
azure-tuki ansible_host=172.207.49.224 ansible_user=AUP ansible_ssh_private_key_file=/home/mark/.ssh/TUKI_key.pem

[tuki_contabo]
contabo-tuki ansible_host=CONTABO_IP ansible_user=TUKI

[tuki_hosthatch]
hosthatch-tuki ansible_host=HOSTHATCH_IP ansible_user=TUKI